# Generated by Django 5.1.15 on 2026-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthProfessional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome_social", models.CharField(max_length=150)),
                ("profissao", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=255)),
                ("contato", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nome_social"],
            },
        ),
    ]
